### ISSUE TITLE
在太极 Magisk 上启动失败

### ISSUE THREAD

**Issue by hjkcai** [zhudongya123/WechatChatRoomHelper#18]
机型：一加 6T
系统：9.0.0（2018年12月安全更新，HOS 9.0.11）
微信：7.0.3（酷安）
群消息助手：1.4.4
太极：4.3.5（Magisk 4.6.0，https://github.com/tiann/Tai-Chi/issues/222，也尝试过 Magisk 4.2.0）
其它模块：
* Storage Redirect (Enhanced 17)
* 微信增强 1.9.1
* 指纹支付 3.9.2

运行微信后，显示 “太极已阻止微信闪退” 的 toast，禁用其它模块也还是一样

完整 logcat：[logcat.txt](https://github.com/zhudongya123/WechatChatRoomHelper/files/2879834/logcat.txt)

logcat 中与群聊助手有关的错误：

```
02-19 19:45:17.255 22553 22599 W System.err: kotlin.UninitializedPropertyAccessException: lateinit property originAdapter has not been initialized
02-19 19:45:17.256 22553 22599 W System.err:    at 02-19 19:45:17.256 22553 22599 W System.err:    at com.zdy.project.wechat_chatroom_helper.wechat.plugins.hook.message.MessageFactory.getAllChatRoom(MessageFactory.kt:43)
02-19 19:45:17.256 22553 22599 W System.err:    at com.zdy.project.wechat_chatroom_helper.wechat.plugins.hook.message.MessageFactory.getSpecChatRoom(MessageFactory.kt:60)
com.zdy.project.wechat_chatroom_helper.wechat.plugins.hook.adapter.MainAdapter.getOriginAdapter(MainAdapter.kt:36)
02-19 19:45:17.256 22553 22599 W System.err:    at com.zdy.project.wechat_chatroom_helper.wechat.plugins.hook.message.MessageFactory.buildChatInfoModelByCursor(MessageFactory.kt:136)
02-19 19:45:17.256 22553 22599 W System.err:    at com.zdy.project.wechat_chatroom_helper.wechat.plugins.hook.message.MessageHandler$executeHook$queryHook$1.afterHookedMethod(MessageHandler.kt:214)
02-19 19:45:17.256 22553 22599 W System.err:    at de.robv.android.xposed.DexposedBridge.handleHookedArtMethod(SourceFile:275)
02-19 19:45:17.256 22553 22599 W System.err:    at de.robv.android.xposed.DexposedBridge.handleHookedArtMethod(SourceFile:205)
02-19 19:45:17.256 22553 22599 W System.err:    at com.tencent.wcdb.database.SQLiteDatabaseX3756854444.rawQueryWithFactory(Unknown Source:23)
02-19 19:45:17.256 22553 22599 W System.err:    at com.tencent.wcdb.database.SQLiteDatabase.rawQueryWithFactory(SourceFile:1481)
02-19 19:45:17.256 22553 22599 W System.err:    at com.tencent.mm.cf.f.a(SourceFile:627)
02-19 19:45:17.256 22553 22599 W System.err:    at com.tencent.mm.cf.h.a(SourceFile:462)
02-19 19:45:17.256 22553 22599 W System.err:    at com.tencent.mm.cf.h.rawQuery(SourceFile:478)
02-19 19:45:17.256 22553 22599 W System.err:    at com.tencent.mm.storage.al.z(SourceFile:1750)
02-19 19:45:17.256 22553 22599 W System.err:    at com.tencent.mm.model.t.e(SourceFile:77)
02-19 19:45:17.256 22553 22599 W System.err:    at com.tencent.mm.l.f.LJ(SourceFile:215)
02-19 19:45:17.256 22553 22599 W System.err:    at com.tencent.mm.plugin.notification.d.f.bx(SourceFile:158)
02-19 19:45:17.256 22553 22599 W System.err:    at com.tencent.mm.model.p.onAccountInitialized(SourceFile:168)
02-19 19:45:17.256 22553 22599 W System.err:    at com.tencent.mm.kernel.a.c$4.call(SourceFile:1247)
02-19 19:45:17.256 22553 22599 W System.err:    at com.tencent.mm.kernel.a.b.e$1.run(SourceFile:1189)
02-19 19:45:17.256 22553 22599 W System.err:    at android.os.Handler.handleCallback(Handler.java:873)
02-19 19:45:17.256 22553 22599 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
02-19 19:45:17.256 22553 22599 W System.err:    at android.os.Looper.loop(Looper.java:193)
02-19 19:45:17.256 22553 22599 W System.err:    at android.os.HandlerThread.run(HandlerThread.java:65)
```

```
02-19 19:45:17.405 22553 22553 I DexposedBridge: java.lang.IllegalStateException: telephonyManager.deviceId must not be null
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at com.zdy.project.wechat_chatroom_helper.utils.DeviceUtils.getIMELCode(DeviceUtils.kt:17)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at com.zdy.project.wechat_chatroom_helper.wechat.chatroomView.ChatRoomView.<init>(ChatRoomView.kt:101)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at com.zdy.project.wechat_chatroom_helper.wechat.chatroomView.ChatRoomViewPresenter.<init>(ChatRoomViewPresenter.kt:32)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at com.zdy.project.wechat_chatroom_helper.wechat.plugins.hook.main.MainLauncherUI$executeHook$1.afterHookedMethod(MainLauncherUI.kt:54)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at de.robv.android.xposed.DexposedBridge.handleHookedArtMethod(SourceFile:275)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at de.robv.android.xposed.DexposedBridge.handleHookedArtMethod(SourceFile:205)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at android.app.ActivityX1886887508.onCreate(Unknown Source:9)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at android.support.v4.app.SupportActivity.onCreate(SourceFile:66)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at android.support.v4.app.FragmentActivity.onCreate(SourceFile:321)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at android.support.v7.app.AppCompatActivity.onCreate(SourceFile:84)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at com.tencent.mm.ui.MMFragmentActivity.onCreate(SourceFile:104)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at com.tencent.mm.ui.LauncherUI.onCreate(SourceFile:164)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at android.app.Activity.performCreate(Activity.java:7149)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at android.app.Activity.performCreate(Activity.java:7140)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3017)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3172)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:4920)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4829)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:55)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:4879)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at android.app.ActivityThread.access$3400(ActivityThread.java:207)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at android.os.Handler.dispatchMessage(Handler.java:106)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at android.os.Looper.loop(Looper.java:193)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at android.app.ActivityThread.main(ActivityThread.java:6863)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at java.lang.reflect.Method.invoke(Native Method)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
02-19 19:45:17.405 22553 22553 I DexposedBridge:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

这个错误显示在了 “太极已阻止微信闪退” 的 toast 中：
```
02-19 19:45:17.710 22553 22553 I DexposedBridge: kotlin.UninitializedPropertyAccessException: lateinit property chatRoomViewPresenter has not been initialized
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at com.zdy.project.wechat_chatroom_helper.wechat.plugins.RuntimeInfo.getChatRoomViewPresenter(RuntimeInfo.kt:14)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at com.zdy.project.wechat_chatroom_helper.wechat.plugins.hook.message.MessageHandler$executeHook$queryHook$1.afterHookedMethod(MessageHandler.kt:165)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at de.robv.android.xposed.DexposedBridge.handleHookedArtMethod(SourceFile:275)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at de.robv.android.xposed.DexposedBridge.handleHookedArtMethod(SourceFile:205)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at com.tencent.wcdb.database.SQLiteDatabaseX3756854444.rawQueryWithFactory(Unknown Source:23)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at com.tencent.wcdb.database.SQLiteDatabase.rawQueryWithFactory(SourceFile:1481)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at com.tencent.mm.cf.f.a(SourceFile:627)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at com.tencent.mm.cf.h.a(SourceFile:462)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at com.tencent.mm.storage.al.a(SourceFile:1453)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at com.tencent.mm.ui.conversation.h.dqZ(SourceFile:1582)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at com.tencent.mm.ui.f.getCount(SourceFile:3316)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at java.lang.reflect.Method.invoke(Native Method)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at me.weishu.epic.art2.EpicNative.invoke(Native Method)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.a.air.a(SourceFile:256)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at de.robv.android.xposed.DexposedBridge.invokeOriginalMethod(SourceFile:538)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at de.robv.android.xposed.DexposedBridge.handleHookedArtMethod(SourceFile:259)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at de.robv.android.xposed.DexposedBridge.handleHookedArtMethod(SourceFile:205)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at com.tencent.mm.ui.fX3756862416.getCount(Unknown Source:8)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.widget.HeaderViewListAdapter.getCount(HeaderViewListAdapter.java:132)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.widget.ListView.setAdapter(ListView.java:579)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at com.tencent.mm.ui.conversation.MainUI.dqx(SourceFile:3233)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at com.tencent.mm.ui.AbstractTabChildActivity$AbStractTabFragment.dqJ(SourceFile:148)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at com.tencent.mm.ui.AbstractTabChildActivity$AbStractTabFragment.dqK(SourceFile:184)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at com.tencent.mm.ui.AbstractTabChildActivity$AbStractTabFragment.onResume(SourceFile:2122)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at com.tencent.mm.ui.conversation.MainUI.onResume(SourceFile:139)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.support.v4.app.Fragment.performResume(SourceFile:2390)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1474)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(SourceFile:1759)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1827)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.support.v4.app.b.ci(SourceFile:797)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.support.v4.app.FragmentManagerImpl.executeOps(SourceFile:2596)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(SourceFile:2383)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(SourceFile:2338)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.support.v4.app.FragmentManagerImpl.execSingleAction(SourceFile:2215)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.support.v4.app.b.commitNowAllowingStateLoss(SourceFile:649)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.support.v4.app.l.finishUpdate(SourceFile:167)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at com.tencent.mm.ui.mogic.WxViewPager.populate(SourceFile:1001)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at com.tencent.mm.ui.mogic.WxViewPager.populate(SourceFile:847)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at com.tencent.mm.ui.mogic.WxViewPager.onMeasure(SourceFile:1370)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.view.View.measure(View.java:23355)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.view.View.measure(View.java:23355)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.view.View.measure(View.java:23355)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.support.v7.widget.ContentFrameLayout.onMeasure(SourceFile:141)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.view.View.measure(View.java:23355)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(SourceFile:400)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.view.View.measure(View.java:23355)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.view.View.measure(View.java:23355)
02-19 19:45:17.710 22553 22553 I DexposedBridge:    at android.view.ViewGroup.measureChildWit
```

**Comment by zhudongya123** [comment]
这个是你微信的拨打电话的权限没有授予。
